### ISSUE TITLE
Calver search and replace failing

### ISSUE THREAD

**Issue by scottyhq** [pangeo-bot/dispatcher#7]
The workflow seems to have trouble with 2 month digits versus 1:

```
Run jacobtomlinson/gha-find-replace@0.1.2
  with:
    include: meta.yaml
    find: pangeo-dask =.*
    replace: pangeo-dask =2023.1.4
```
```
pangeo-dask                 2023.1.4      hd8ed1ab_0  conda-forge         
pangeo-dask               2023.01.11      hd8ed1ab_0  conda-forge         
pangeo-dask               2023.01.13      hd8ed1ab_0  conda-forge  
```

the 2023.1.4 was from this PR cc @yuvipanda
https://github.com/conda-forge/pangeo-dask-feedstock/pull/104/files
